<?php
session_start();
include('session.php');
include('../dbcon.php');
require('../fpdf/fpdf.php');


$pdf = new FPDF('L','mm','A4');
$p_width = $pdf->GetPageWidth();
$p_height = $pdf->GetPageHeight();
$X = $pdf->GetX();
$Y = $pdf->GetY();
$pdf->AddPage();
$pdf->Image('../images/logo.png',100,4,15);
$pdf->SetFont('Arial','B',9);
$pdf->SetY($pdf->GetY()-10);
$pdf->Cell("","20",'Republic of the Philippines','','1','C');
$pdf->SetFont('Arial','B',14);
$pdf->SetY($pdf->GetY()-15);
$pdf->Cell("","20",'Bulacan State University','','1','C');
$pdf->SetY($pdf->GetY()-5);
$pdf->SetFont('Helvetica','B',9);
$pdf->Cell("","10","SUMMARY OF UNSERVICEABLE PROPERTY","","1","C");
$pdf->Cell(200,5,"INVENTORY","1","","C");
$pdf->Cell(78,5,"INSPECTION and DISPOSAL","1","1","C");
$pdf->SetFont('Helvetica','',7);

$pdf->MultiCell(12,5,"Date Acquired","1","C","");
$pdf->SetXY($pdf->GetX()+12,$pdf->GetY() -10);
$pdf->Cell(30,10,"Particulars / Articles","1","","C");
$pdf->MultiCell(12,5,"Property No.","1","C","");
$pdf->SetXY($pdf->GetX()+54,$pdf->GetY() -10);
$pdf->Cell(5,10,"Qty","1","","C");
$pdf->Cell(13,10,"Unit Cost","1","","C");
$pdf->Cell(13,10,"Total Cost","1","","C");
$pdf->MultiCell(14,5,"Date Returned","1","C","");
$pdf->SetXY($pdf->GetX()+99,$pdf->GetY() -10);
$pdf->MultiCell(12,3.339,"No of Years in Service","1","C","");
$pdf->SetXY($pdf->GetX()+111,$pdf->GetY() -10);
$pdf->MultiCell(12,3.339,"Office / College / Campus","1","C","");
$pdf->SetXY($pdf->GetX()+123,$pdf->GetY() -10);
$pdf->MultiCell(13,5,"Name of Employee","1","C","");
$pdf->SetXY($pdf->GetX()+136,$pdf->GetY() -10);
$pdf->MultiCell(17,5,"Accumulated Depreciation","1","C","");
$pdf->SetXY($pdf->GetX()+153,$pdf->GetY() -10);
$pdf->MultiCell(18,3.34,"Accumulated inpairment Losses","1","C","");
$pdf->SetXY($pdf->GetX()+171,$pdf->GetY() -10);
$pdf->MultiCell(12.6,5,"Carrying Amount","1","C","");
$pdf->SetXY($pdf->GetX()+183.7,$pdf->GetY() -10);
$pdf->Cell(16.3,10,"Remarks","1","","C");
$pdf->Cell(40,5,"DISPOSAL","1","","C");
$pdf->MultiCell(13.7,5,"Appraised Value","1","C","");
$pdf->SetXY($pdf->GetX()+253.8,$pdf->GetY() -10);
$pdf->Cell(24,5,"RECORD OF SALES","1","1","C");
$pdf->SetXY($pdf->GetX()+200,$pdf->GetY());
$pdf->SetFont('Helvetica','',5);
$pdf->Cell(40/5,5,"SALE","1","","C");
$pdf->SetFont('Helvetica','',4);
$pdf->Cell(40/5,5,"TRANSFER","1","","C");
$pdf->Cell(40/5,5,"Destruction","1","","C");
$pdf->MultiCell(40/5,2.5,"Others (Specify)","1","C","");
$pdf->SetXY($pdf->GetX()+232,$pdf->GetY()-5);
$pdf->Cell(40/5,5,"Total","1","1","C");
$pdf->SetXY($pdf->GetX()+253.8,$pdf->GetY()-5);
$pdf->Cell(24/2,5,"OR No","1","","C");
$pdf->Cell(24/2,5,"Amount","1","1","C");
$sql = $conn->query("select * from disposal_request where id = ". $_GET['id']);
$data = $sql->fetch_assoc();
$pdf->SetFont('Helvetica','',5);
$pdf->Cell(24/2,5,$data['date_acquired'],"1","0","C");
$pdf->SetFont('Helvetica','',7);
$pdf->Cell(30,5,$data['particulars_articles'],"1","0","C");
$pdf->SetFont('Helvetica','',5);
$pdf->Cell(12,5,"_________","1","0","C");
$pdf->Cell(5,5,$data['qty'],"1","0","C");
$pdf->SetFont('Helvetica','',6);
$pdf->Cell(13,5,'Php '. $data['unit_cost'],"1","0","C");
$pdf->Cell(13,5,'Php '. $data['total_cost'],"1","0","C");
$pdf->Cell(14,5,'_________',"1","0","C");
$pdf->Cell(12,5,'_________',"1","0","C");
//get college info
$sql_coll = $conn->query("select emp.*,coll.* from tbl_supplier_employee emp inner join tbl_branch coll on emp.college = coll.branchID where emp.id= ".$data['name_of_employee']);
$data_coll = $sql_coll->fetch_assoc();
$pdf->MultiCell(12,2.5,$data_coll['branch'],"1","0","");
$pdf->SetXY($pdf->GetX() + 123,$pdf->GetY() - 5);
$pdf->MultiCell(13,2.5,$data_coll['first_name'] .' '. $data_coll['last_name'],"1","0","");
$pdf->SetXY($pdf->GetX()+136,$pdf->GetY()-5);
$pdf->Cell(17,5,"___________","1","0","C");
$pdf->Cell(18,5,"___________","1","0","C");
$pdf->Cell(12.6,5,"________","1","0","C");
$pdf->Cell(16.3,5,"________","1","0","C");
$pdf->Cell(40/5,5,"","1","0","C");
$pdf->Cell(40/5,5,"","1","0","C");
$pdf->Cell(40/5,5,"","1","0","C");
$pdf->Cell(40/5,5,"","1","0","C");
$pdf->Cell(40/5,5,"","1","0","C");
$pdf->Cell(13.7,5,"","1","0","C");
$pdf->Cell(24/2,5,"","1","0","C");
$pdf->Cell(24/2,5,"","1","0","C");
$pdf->Ln(10);
$pdf->SetFont('Helvetica','',7);
$pdf->Cell(20,'10','I HEREBY request inspection and disposition, pursuant to Section 79 of PD 1445, of the property enumerated above.','','1');
$pdf->Output();